const DEFAULT_PROJECTS = [
    {
        id: 'def-101',
        category: 'Web Development',
        title: 'High-Performance E-commerce Platform Build',
        description: 'Develop a custom, scalable e-commerce website using Next.js and headless commerce APIs.',
        banner_url: 'https://media.istockphoto.com/id/1428709516/photo/shopping-online-woman-hand-online-shopping-on-laptop-computer-with-virtual-graphic-icon.jpg?s=612x612&w=0&k=20&c=ROAncmFL4lbSQdU4VOhyXu-43ngzfEqHE5ZZAw5FtYk=',
        max_budget: 6500,
        posted_by: 'GlobalCommerce Inc.',
        time_commitment: '3-6 Months',
        level: 'Expert',
        is_verified: true,
    },
    {
        id: 'def-102',
        category: 'Design',
        title: 'Mobile App UI/UX Redesign',
        banner_url: 'https://www.aufaitux.com/wp-content/uploads/2020/05/UIUX-designing-1.jpg',
        description: 'Complete redesign of an existing fitness tracking mobile app to improve user engagement and usability.',
        max_budget: 3200,
        posted_by: 'FitTrack Solutions',
        time_commitment: '1 Month',
        level: 'Mid-Senior',
        is_verified: true,
    },
    {
        id: 'def-103',
        category: 'Writing / Content',
        title: 'SEO-Optimized Tech Blog Content',
        banner_url: 'https://media.istockphoto.com/id/902787158/photo/woman-hands-with-pen-writing-on-notebook-in-the-office.jpg?s=612x612&w=0&k=20&c=AFrTZ8bU1XrEifN4GU57k9PK8HYd3a3whGB_0pFp29E=',
        description: 'Need a writer for 10 high-quality, long-form articles focused on AI and Machine Learning trends.',
        max_budget: 1800,
        posted_by: 'AITrends Magazine',
        time_commitment: '1-2 Weeks',
        level: 'Intermediate',
        is_verified: true,
    },
    {
        id: 'def-104',
        category: 'Data Science',
        title: 'Predictive Sales Forecasting Model',
         banner_url: 'https://plus.unsplash.com/premium_photo-1661878265739-da90bc1af051?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZGF0YSUyMHNjaWVuY2V8ZW58MHx8MHx8fDA%3D',
        description: 'Build and validate a Python-based predictive model to forecast quarterly sales based on historical data.',
        max_budget: 4800,
        posted_by: 'DataCorp Analysts',
        time_commitment: '2 Months',
        level: 'Expert',
        is_verified: true,
    },
    {
        id: 'def-105',
        category: 'Web Development',
        title: 'Landing Page Optimization & A/B Testing',
        banner_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTUaWanp_Q6Glp0JGy1eHZ-QJ-iBnoCk5SDQ&s',
        description: 'Design and implement two variations of a landing page for conversion rate optimization.',
        max_budget: 900,
        posted_by: 'Marketing Pros',
        time_commitment: '1 Week',
        level: 'Junior',
        is_verified: true,
    },
    {
        id: 'def-106',
        category: 'Marketing & Sales',
        title: 'Google Ads Campaign Setup & Management',
        banner_url: 'https://img.freepik.com/premium-photo/marketing-digital-technology-business-concept-uds_31965-305041.jpg?semt=ais_hybrid&w=740&q=80',
        description: 'Set up, launch, and manage a new search and display campaign for a SaaS product launch.',
        max_budget: 2100,
        posted_by: 'CloudStartups LLC',
        time_commitment: 'Ongoing',
        level: 'Mid-Senior',
        is_verified: true,
    },
    {
        id: 'def-107',
        category: 'Design',
        title: '3D Mockup and Animation for Product',
         banner_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKMWrU085MStjVj16kgKsQsOStea_8oQshrw&s',
        description: 'Create photorealistic 3D models and short animated videos for a new line of electronic gadgets.',
        max_budget: 4500,
        posted_by: 'Gadget Makers',
        time_commitment: '4 Weeks',
        level: 'Expert',
        is_verified: true,
    },
    {
        id: 'def-108',
        category: 'Web Development',
        title: 'Backend API Migration to Microservices',
        banner_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhbANFPDI-qc0tGsjwG1G6xt10TfN5ktd6fSTIBkctbXqli6wxJuLhnZF5PZ7sgW1AbhI&usqp=CAU',
        description: 'Migrate a monolithic Python/Django backend to a modern, scalable microservices architecture using Docker and Kubernetes.',
        max_budget: 8000,
        posted_by: 'Tech Innovators',
        time_commitment: '6 Months',
        level: 'Expert',
        is_verified: true,
    },
    {
        id: 'def-109',
        category: 'Writing / Content',
        title: 'E-book Ghostwriting: Finance Guide',
        banner_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAbe9etU76MCMG2JSOTXp3ZRReTmm4rMjH7G-sckrUQGHRhAAY5pc1n6ZWTWia4Xc3NKg&usqp=CAU',
        description: 'Write a comprehensive 50-page e-book on personal finance and investment strategies.',
        max_budget: 2800,
        posted_by: 'Finance Educators',
        time_commitment: '3 Weeks',
        level: 'Mid-Senior',
        is_verified: true,
    },
    {
        id: 'def-110',
        category: 'Data Science',
        title: 'Natural Language Processing (NLP) Sentiment Analysis',
        banner_url: 'https://t4.ftcdn.net/jpg/04/11/50/99/360_F_411509944_NHQwlYfg1td6fBQyyHLdlfltmlv8cmAp.jpg',
        description: 'Develop an NLP model to analyze customer sentiment from social media posts and reviews.',
        max_budget: 5500,
        posted_by: 'SocialMetrics Co.',
        time_commitment: '2 Months',
        level: 'Expert',
        is_verified: true,
    },
    {
        id: 'def-111',
        category: 'Marketing & Sales',
        title: 'LinkedIn Lead Generation Strategy',
         banner_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPbJ7WXVETcz7uB1CX2QIYbLNVWNzKG30uCKLTGv-EafibbYfkLs0fMy5_oDi2L-eNIyY&usqp=CAU',
        description: 'Develop and execute a targeted LinkedIn strategy to generate qualified B2B sales leads.',
        max_budget: 1500,
        posted_by: 'B2B Connect',
        time_commitment: '1 Month',
        level: 'Intermediate',
        is_verified: true,
    },
    {
        id: 'def-112',
        category: 'Design',
        title: 'Company Rebranding & Style Guide',
         banner_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHG-x5a01GBmiV1FfYtVAYBXVONe59xILgsw&s',
        description: 'Create a new logo, color palette, typography, and a detailed brand style guide.',
        max_budget: 3800,
        posted_by: 'Brand Revival',
        time_commitment: '5 Weeks',
        level: 'Mid-Senior',
        is_verified: true,
    },
    {
        id: 'def-113',
        category: 'Web Development',
        title: 'Accessibility Audit (WCAG 2.1) & Implementation',
         banner_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRU5RDI_MOIIFFydha1aRa78iwhHddG8ffCOgvaGR5s9mNs2BjeLOWXQTBg7tQMYLxA6vY&usqp=CAU',
        description: 'Conduct a full accessibility audit of existing corporate site and implement required changes to meet WCAG 2.1 AA standards.',
        max_budget: 4000,
        posted_by: 'AccessForAll NGO',
        time_commitment: '3 Weeks',
        level: 'Expert',
        is_verified: true,
    },
    {
        id: 'def-114',
        category: 'Data Science',
        title: 'Data Pipeline Setup (ETL) on AWS',
        banner_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSkO9wRMl9SstWLR1mO1Ytst0obqi72mpzVw&s',
        description: 'Set up an automated ETL pipeline to ingest data from various sources into a centralized AWS Redshift warehouse.',
        max_budget: 6000,
        posted_by: 'DataFlow Systems',
        time_commitment: '4 Weeks',
        level: 'Expert',
        is_verified: true,
    },
    {
        id: 'def-115',
        category: 'Writing / Content',
        title: 'Video Scriptwriting for Explainer Videos',
        banner_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRINFdUvz1ypDOu0_24zoNY4BkoHXUy3H-uCw&s',
        description: 'Write engaging and concise scripts for a series of five 90-second animated explainer videos.',
        max_budget: 1100,
        posted_by: 'Animation Studio X',
        time_commitment: '1 Week',
        level: 'Junior',
        is_verified: true,
    },
    {
        id: 'def-116',
        category: 'Marketing & Sales',
        title: 'Email Newsletter Design & Automation',
        banner_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlW4JtB-0dslAasiWzjFcpwYX8cKEgysiL1Q&s',
        description: 'Design a responsive email template and set up automation workflows in Mailchimp/Klaviyo.',
        max_budget: 1300,
        posted_by: 'E-com Boosters',
        time_commitment: '2 Weeks',
        level: 'Intermediate',
        is_verified: true,
    },
    {
        id: 'def-117',
        category: 'Web Development',
        title: 'Technical Documentation & API Reference',
        banner_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRe_YorWFDWE7luNnwWVx-ygomn80lY8g5-AA&s',
        description: 'Create comprehensive and clear technical documentation for a new public-facing REST API.',
        max_budget: 2500,
        posted_by: 'DevTools Corp.',
        time_commitment: '3 Weeks',
        level: 'Mid-Senior',
        is_verified: true,
    },
];

module.exports = { DEFAULT_PROJECTS };