export const projectsData = [
  {
    id: 1,
    imgUrl: "https://res.cloudinary.com/vistaprint/images/c_scale,w_448,h_299,dpr_2/f_auto,q_auto/v1719942393/ideas-and-advice-prod/blogadmin/logo-chanel/logo-chanel.png?_i=AA",
    title: "Build a Portfolio Website",
    description: "Need a React developer to build a personal portfolio site.",
    budget: 200,
    category: "Web Development",
    postedBy: "John Doe",
  },
  {
    id: 2,
    imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3Vlgdbtq7w4yKGX3YyZnZmaOnTH41YN2zDg&s",
    title: "Logo Design for Brand",
    description: "Looking for creative designer for logo work.",
    budget: 100,
    category: "Design",
    postedBy: "Jane Smith",
  },
  {
    id: 3,
    imgUrl: "https://res.cloudinary.com/vistaprint/images/w_1024,h_389,c_scale,w_1024,h_389,dpr_1.25/f_auto,q_auto/v1719942405/ideas-and-advice-prod/blogadmin/nike-logo/nike-logo.png?_i=AA",
    title: "E-commerce Mobile App Development",
    description: "Full-stack development of an iOS and Android e-commerce application using Flutter/React Native.",
    budget: 4500,
    category: "Mobile Development",
    postedBy: "Tech Solutions Inc.",
  },
  {
    id: 4,
    imgUrl: "https://res.cloudinary.com/vistaprint/images/w_1024,h_389,c_scale,w_1024,h_389,dpr_1.25/f_auto,q_auto/v1719942405/ideas-and-advice-prod/blogadmin/nike-logo/nike-logo.png?_i=AA",
    title: "Sales Data Analysis and Visualization",
    description: "Analyze Q3 sales data and create interactive dashboards in Power BI or Tableau.",
    budget: 800,
    category: "Data Science",
    postedBy: "Alpha Marketing",
  },
  {
    id: 5,
    imgUrl: "https://res.cloudinary.com/vistaprint/images/w_1024,h_576,c_scale,w_1024,h_575,dpr_1.25/f_auto,q_auto/v1719942378/ideas-and-advice-prod/blogadmin/apple-logo/apple-logo.png?_i=AA",
    title: "SEO-Optimized Blog Content Writer",
    description: "Write 10 articles (1000 words each) focused on digital marketing trends with keyword research.",
    budget: 500,
    category: "Content Writing",
    postedBy: "Content Hub",
  },
  {
    id: 6,
    imgUrl: "https://res.cloudinary.com/vistaprint/images/c_scale,w_600,h_556,dpr_1.25/f_auto,q_auto/v1719942431/ideas-and-advice-prod/blogadmin/shell-logo/shell-logo.png?_i=AA",
    title: "Manage Social Media Campaigns",
    description: "Manage and run paid ad campaigns on Facebook and Instagram for 3 months.",
    budget: 1200,
    category: "Marketing",
    postedBy: "Retail Outlet Co.",
  },
  {
    id: 7,
    imgUrl: "https://res.cloudinary.com/vistaprint/images/c_scale,w_600,h_556,dpr_1.25/f_auto,q_auto/v1719942431/ideas-and-advice-prod/blogadmin/shell-logo/shell-logo.png?_i=AA",
    title: "User Experience (UX) Research and Testing",
    description: "Conduct usability testing and interviews for an existing SaaS application and deliver a report.",
    budget: 1500,
    category: "Design",
    postedBy: "SaaS Innovators",
  },
  {
    id: 8,
    imgUrl: "https://res.cloudinary.com/vistaprint/images/c_scale,w_600,h_556,dpr_1.25/f_auto,q_auto/v1719942431/ideas-and-advice-prod/blogadmin/shell-logo/shell-logo.png?_i=AA",
    title: "Develop REST API for Inventory System",
    description: "Build a secure and scalable backend REST API using Node.js/Python for inventory management.",
    budget: 2800,
    category: "Web Development",
    postedBy: "Global Logistics",
  },
  {
    id: 9,
    imgUrl: "https://res.cloudinary.com/vistaprint/images/c_scale,w_1048,h_342,dpr_1.25/f_auto,q_auto/v1706089184/ideas-and-advice-prod/en-us/Coca-Cola_logo.svg_/Coca-Cola_logo.svg_.png?_i=AA",
    title: "Short Explainer Video Editing",
    description: "Edit raw footage into a polished 60-second animated explainer video.",
    budget: 400,
    category: "Video & Animation",
    postedBy: "Startup Launchpad",
  },
  {
    id: 10,
    imgUrl: "https://res.cloudinary.com/vistaprint/images/c_scale,w_448,h_204,dpr_1.25/f_auto,q_auto/v1719942403/ideas-and-advice-prod/blogadmin/nasa-logo/nasa-logo.png?_i=AA",
    title: "Audio Transcription Services",
    description: "Transcribe 10 hours of academic interview audio into text with high accuracy.",
    budget: 250,
    category: "Virtual Assistant",
    postedBy: "University Researcher",
  },
  {
    id: 11,
    imgUrl: "https://res.cloudinary.com/vistaprint/images/c_scale,w_448,h_204,dpr_1.25/f_auto,q_auto/v1719942403/ideas-and-advice-prod/blogadmin/nasa-logo/nasa-logo.png?_i=AA",
    title: "Website Security Audit (Pen-Testing)",
    description: "Perform a comprehensive security audit and penetration test on a live WordPress site.",
    budget: 950,
    category: "Cybersecurity",
    postedBy: "E-commerce Secure",
  },
  {
    id: 12,
    imgUrl: "https://res.cloudinary.com/vistaprint/images/c_scale,w_448,h_204,dpr_1.25/f_auto,q_auto/v1719942403/ideas-and-advice-prod/blogadmin/nasa-logo/nasa-logo.png?_i=AA",
    title: "SQL Database Optimization",
    description: "Review and optimize slow queries and database schema for an existing MySQL database.",
    budget: 600,
    category: "Data Science",
    postedBy: "Database Masters",
  },
  {
    id: 13,
    imgUrl: "https://res.cloudinary.com/vistaprint/images/c_scale,w_693,h_319,dpr_1.25/f_auto,q_auto/v1719942391/ideas-and-advice-prod/blogadmin/ibm-logo/ibm-logo.png?_i=AA",
    title: "Sales Page Copywriting",
    description: "Write compelling, high-converting copy for a new product landing/sales page.",
    budget: 700,
    category: "Content Writing",
    postedBy: "Product Innovators",
  },
  {
    id: 14,
    imgUrl: "https://res.cloudinary.com/vistaprint/images/c_scale,w_693,h_319,dpr_1.25/f_auto,q_auto/v1719942391/ideas-and-advice-prod/blogadmin/ibm-logo/ibm-logo.png?_i=AA",
    title: "Product Photo Retouching",
    description: "Batch retouch 50 product photos for Amazon listing (color correction, background removal).",
    budget: 350,
    category: "Design",
    postedBy: "Online Retailer",
  },
  {
    id: 15,
    imgUrl: "https://res.cloudinary.com/vistaprint/images/w_1024,h_780,c_scale,w_1024,h_782,dpr_1.25/f_auto,q_auto/v1719942436/ideas-and-advice-prod/blogadmin/playstation-logo/playstation-logo.png?_i=AA",
    title: "Unity 2D Game Asset Creation",
    description: "Design and deliver a full set of sprites and animations for a new 2D platformer game.",
    budget: 1800,
    category: "Game Development",
    postedBy: "Indie Game Studio",
  },
  {
    id: 16,
    imgUrl: "https://res.cloudinary.com/vistaprint/images/w_1024,h_309,c_scale,w_1024,h_309,dpr_1.25/f_auto,q_auto/v1719942376/ideas-and-advice-prod/blogadmin/amazon-logo/amazon-logo.png?_i=AA",
    title: "English to Spanish Translation",
    description: "Translate a 15,000-word legal document from English into neutral Spanish.",
    budget: 1100,
    category: "Virtual Assistant",
    postedBy: "Legal Firm P.C.",
  },
  {
    id: 17,
    imgUrl: "https://res.cloudinary.com/vistaprint/images/w_1024,h_507,c_scale,w_1024,h_507,dpr_1.25/f_auto,q_auto/v1719942380/ideas-and-advice-prod/blogadmin/barbie-logo/barbie-logo.png?_i=AA",
    title: "AWS Cloud Migration Specialist",
    description: "Migrate an existing on-premise application infrastructure to AWS using Terraform.",
    budget: 5000,
    category: "DevOps",
    postedBy: "Cloud Services Ltd.",
  },
  {
    id: 18,
    imgUrl: "https://res.cloudinary.com/vistaprint/images/w_1024,h_507,c_scale,w_1024,h_507,dpr_1.25/f_auto,q_auto/v1719942380/ideas-and-advice-prod/blogadmin/barbie-logo/barbie-logo.png?_i=AA",
    title: "Email Marketing Campaign Setup",
    description: "Set up and automate a 5-part welcome email sequence in Mailchimp/Klaviyo.",
    budget: 450,
    category: "Marketing",
    postedBy: "Subscription Box Co.",
  },
  {
    id: 19,
    imgUrl: "https://res.cloudinary.com/vistaprint/images/w_1024,h_507,c_scale,w_1024,h_507,dpr_1.25/f_auto,q_auto/v1719942380/ideas-and-advice-prod/blogadmin/barbie-logo/barbie-logo.png?_i=AA",
    title: "Customer Support Chatbot Development",
    description: "Develop and integrate an AI-powered customer support chatbot using Dialogflow/Rasa.",
    budget: 3200,
    category: "AI/ML",
    postedBy: "E-Service Provider",
  },
  {
    id: 20,
    imgUrl: "https://res.cloudinary.com/vistaprint/images/w_1024,h_287,c_scale,w_1024,h_287,dpr_1.25/f_auto,q_auto/v1719942389/ideas-and-advice-prod/blogadmin/fedex-logo/fedex-logo.png?_i=AA",
    title: "Technical Documentation Writer",
    description: "Write comprehensive technical documentation and API reference guides for a new software product.",
    budget: 1400,
    category: "Content Writing",
    postedBy: "Software House",
  },
  {
    id: 21,
    imgUrl: "https://res.cloudinary.com/vistaprint/images/w_1024,h_287,c_scale,w_1024,h_287,dpr_1.25/f_auto,q_auto/v1719942389/ideas-and-advice-prod/blogadmin/fedex-logo/fedex-logo.png?_i=AA",
    title: "Custom WordPress Theme Development",
    description: "Develop a custom, lightweight, and responsive WordPress theme based on provided mockups.",
    budget: 2500,
    category: "Web Development",
    postedBy: "Blogging Platform",
  },
  {
    id: 22,
    imgUrl: "https://res.cloudinary.com/vistaprint/images/w_1024,h_287,c_scale,w_1024,h_287,dpr_1.25/f_auto,q_auto/v1719942389/ideas-and-advice-prod/blogadmin/fedex-logo/fedex-logo.png?_i=AA",
    title: "iOS App Bug Fixing",
    description: "Identify and resolve 10 known critical bugs in an existing Swift-based iOS application.",
    budget: 750,
    category: "Mobile Development",
    postedBy: "App Maintenance Corp.",
  },
]